export const LOGINS = [
  {
    id: "1",
    name: "Davi Souza",
    email: "davi@gmail.com",
    password: "1234",
    permission: "Admin",
    telefone: "(79) 9983-6358",
    status: "active",
    department: "TI",
    manager: "Julio Mendes",
    photo: "../img/img_users/davi.png",
  },
  {
    id: "2",
    name: "Lucas Melo",
    email: "lucas@gmail.com",
    password: "1234",
    permission: "Gestor",
    telefone: "(79) 9974-2374",
    status: "active",
    department: "RH",
    manager: "Aline Machado",
    photo: "../img/img_users/lucas.png",
  },
  {
    id: "3",
    name: "Felipe Melo",
    email: "felipe@gmail.com",
    password: "1234",
    permission: "Usuário",
    telefone: "(79) 9933-1254",
    status: "active",
    department: "Ambulatorio",
    manager: "Carlos Almeida",
    photo: "../img/img_users/user_default.png",
  },
];
